<a href="https://colab.research.google.com/github/nawroz-m/ML_learning/blob/PyTorch/00_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip3 install torch

In [3]:
import torch

In [205]:
import numpy as np

In [8]:
torch.__version__

'2.10.0+cu128'

In [16]:
# 1D Tensor scaler
x=torch.randn(4)
x

tensor([-0.6686,  0.2156, -0.0512, -0.1066])

In [17]:
# 2D Tensor scaler
x2d = torch.randn(2, 4)
x2d


tensor([[-0.1685,  2.3894, -0.1510, -0.0649],
        [ 0.3736,  0.4779,  1.4454,  0.2310]])

In [18]:
# Get the shape of scaler
x2d.shape

torch.Size([2, 4])

In [20]:
# The dimention of the scaler
x2d.ndim

2

In [33]:
# Create vector
vector = torch.tensor([1, 1.2, 2.2, 3, 4.9, 5.2], dtype=torch.int32)

In [34]:
vector

tensor([1, 1, 2, 3, 4, 5], dtype=torch.int32)

In [31]:
# Vector shape
vector.shape

torch.Size([6])

In [35]:
# Type of the vector
vector.dtype

torch.int32

In [39]:
# Matrix
matrix = torch.tensor([[1, 2.3], [3.1, 4.2], [4, 5]], dtype=torch.float32)
matrix

tensor([[1.0000, 2.3000],
        [3.1000, 4.2000],
        [4.0000, 5.0000]])

In [41]:
# The dimention of the matrix
matrix.dim()

2

In [42]:
# The shape of the matrix
matrix.shape

torch.Size([3, 2])

In [44]:
# type of the matrix
matrix.dtype

torch.float32

In [53]:
# Access to the matrix element
matrix[0:-1]

tensor([[1.0000, 2.3000],
        [3.1000, 4.2000]])

In [76]:
# Create a random integer tensor
torch.randint(2, 5, (3,))

tensor([2, 4, 3])

In [5]:
# Create a 5x4 random matrix
rand_matrix = torch.rand([5, 4], dtype=torch.float16)
rand_matrix

tensor([[0.1914, 0.4907, 0.9521, 0.6885],
        [0.2617, 0.9282, 0.2720, 0.5400],
        [0.6436, 0.9253, 0.2085, 0.8438],
        [0.0527, 0.6055, 0.4463, 0.2197],
        [0.0791, 0.1484, 0.6196, 0.2480]], dtype=torch.float16)

In [19]:
rand_matrix.shape

torch.Size([5, 4])

In [30]:
# unsqueez matrix
unsqueezed = torch.unsqueeze(rand_matrix, dim=2)
unsqueezed[1]

tensor([[0.2617],
        [0.9282],
        [0.2720],
        [0.5400]], dtype=torch.float16)

In [31]:
unsqueezed.shape

torch.Size([5, 4, 1])

In [143]:
# Shuffle tensore using merge indexes
t=torch.tensor([[1,2],[3,4]])
r=torch.randperm(2)
c=torch.randperm(2)
t=t[r[:, None], c]
t

tensor([[3, 4],
        [1, 2]])

In [144]:
t.nelement()

4

In [145]:
# Suffle tensor using view the best practice
indx = torch.randperm(t.nelement())
t.view(-1)[indx].view(t.size())

tensor([[2, 4],
        [3, 1]])

In [146]:
t

tensor([[3, 4],
        [1, 2]])

In [151]:
# Create tensor by torch one
torch.ones(5, dtype=torch.int32)

tensor([1, 1, 1, 1, 1], dtype=torch.int32)

In [152]:
# Create zero tensor
torch.zeros(6)

tensor([0., 0., 0., 0., 0., 0.])

In [155]:
# Creating tensor from numpy
num = np.ones(5)
num

array([1., 1., 1., 1., 1.])

In [171]:
# Creating tensor from numpy arange
num_arange = np.arange(3, 8, dtype=np.float32)
num_arange

array([3., 4., 5., 6., 7.], dtype=float32)

In [204]:
shuffled_num = np.random.permutation(num_arange)
shuffled_num

array([4., 5., 7., 6., 3.], dtype=float32)