<a href="https://colab.research.google.com/github/nawroz-m/ML_learning/blob/main/00_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import tensor from Tensorflow

In [ ]:
import tensorflow as tf

# Print the tensor version

In [ ]:
print(tf.__version__)

2.19.0


# Important concept
* Scaler
* Vector
* Matrix
* Tensor




In [ ]:
# Scaler
scale = tf.constant(4)
scale

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [ ]:
scale.ndim

0

In [ ]:
# vector
vector = tf.constant([4, 5])
vector


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 5], dtype=int32)>

In [ ]:
vectortype = tf.constant([1., 2.2], dtype=tf.float32)
vectortype

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1. , 2.2], dtype=float32)>

In [ ]:
# Matrix
matrix = tf.constant([[1,2],
                      [3,4]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
# Tensor
tensor = tf.constant([
    [
        [1, 1],
         [2, 2]
        ],
    [
        [3.1, 3.2],
        [4., 4]]
])
tensor

In [ ]:
tensor.ndim

3

# Create Tensor with Tensorflow Variable

In [ ]:
constant_tensor = tf.constant([[1,2], [3,4]])
variable_tensor = tf.Variable([[1,2], [3,4]])


In [ ]:
constant_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
variable_tensor

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
constant_tensor[0]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [ ]:
variable_tensor[0]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [ ]:
# Reassigne value to tensor
variable_tensor[0] = [2, 2]

In [ ]:
variable_tensor[0].assign(2)

<tf.Variable 'UnreadVariable' shape=(2, 2) dtype=int32, numpy=
array([[2, 2],
       [3, 4]], dtype=int32)>

In [ ]:
context_variable = tf.Variable(9)
context_variable

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=9>

In [ ]:
context_variable.assign(0)
context_variable

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=0>

### Tensorflow constant is not iterable


In [ ]:
constant_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

# 01 - Creating random tensors with Tensorflow


In [ ]:
random_tensor_1 = tf.random.Generator.from_seed(7)
random_tensor_2 = tf.random.Generator.from_seed(8)
random_tensor_1, random_tensor_2

(<tensorflow.python.ops.stateful_random_ops.Generator at 0x7eb7643a0110>,
 <tensorflow.python.ops.stateful_random_ops.Generator at 0x7eb7657cde80>)

In [ ]:
# create random distribution from random tensor

random_tensor_1 = random_tensor_1.normal(shape=(1,2, 3))
random_tensor_2 = random_tensor_2.normal(shape=(1,2, 3))
random_tensor_1, random_tensor_2, random_tensor_1==random_tensor_2

# Shuffle tensor in Tensorflow


In [ ]:
shuffle = tf.constant([[1,2],[3,4], [5,6]])
shuffle


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [ ]:
# Shuffle the random



shuffle_random = tf.random.shuffle(shuffle)
shuffle_random

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[5, 6],
       [1, 2],
       [3, 4]], dtype=int32)>

# Creating a one tensor by Tensorflow one

In [ ]:
tf.ones(shape=(3, 4), dtype=tf.int32)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)>

### Create a zero tensor by Tensorflow zero


In [ ]:
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

# Creating tensor from Numpy

In [ ]:
import numpy as np
print(np.__version__)

2.0.2


In [ ]:
numpy_A = np.ones(shape=(3, 4))
numpy_A

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# Create numpy array with arange
numpy_B = np.arange(5,12, dtype=np.int32)
numpy_B

array([ 5,  6,  7,  8,  9, 10, 11], dtype=int32)

## Creating tensor from the numpy matrix
> Tensor data is much faster in GPU

In [ ]:
A = tf.constant(numpy_A, shape=(2, 3, 2))
A

In [ ]:
B = tf.constant(numpy_B, dtype=tf.float16)
B

<tf.Tensor: shape=(7,), dtype=float16, numpy=array([ 5.,  6.,  7.,  8.,  9., 10., 11.], dtype=float16)>