<a href="https://colab.research.google.com/github/nawroz-m/ML_learning/blob/BigImgSingnal/Lecture_02_Hepatitis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [71]:
import os
from google.colab import files, drive
import pandas as pd
import sklearn.ensemble
import sklearn.metrics
from sklearn.model_selection import train_test_split
import numpy as np


# 1 Load and explore the dataset

In [11]:
# Load file
drive.flush_and_unmount()
drive.mount('/content/drive')

Mounted at /content/drive


In [12]:
df = pd.read_csv("/content/drive/MyDrive/Big Img Sig/hepatitis.csv")

In [13]:
df.head(5)

,age,sex,steroid,antivirals,fatigue,malaise,anorexia,liver_big,liver_firm,spleen_palpable,spiders,ascites,varices,bilirubin,alk_phosphate,sgot,albumin,protime,histology,class
0,30,male,False,False,False,False,False,False,False,False,False,False,False,1.0,85.0,18.0,4.0,NaN,False,live
1,50,female,False,False,True,False,False,False,False,False,False,False,False,0.9,135.0,42.0,3.5,NaN,False,live
2,78,female,True,False,True,False,False,True,False,False,False,False,False,0.7,96.0,32.0,4.0,NaN,False,live
3,31,female,NaN,True,False,False,False,True,False,False,False,False,False,0.7,46.0,52.0,4.0,80.0,False,live
4,34,female,True,False,False,False,False,True,False,False,False,False,False,1.0,NaN,200.0,4.0,NaN,False,live


In [14]:
df.shape

(155, 20)

In [15]:
df.dtypes

,0
age,int64
sex,object
steroid,object
antivirals,bool
fatigue,object
malaise,object
anorexia,object
liver_big,object
liver_firm,object
spleen_palpable,object


In [16]:
# CONVER ALL TYPES
df = df.convert_dtypes()
df.dtypes

,0
age,Int64
sex,string[python]
steroid,boolean
antivirals,boolean
fatigue,boolean
malaise,boolean
anorexia,boolean
liver_big,boolean
liver_firm,boolean
spleen_palpable,boolean


In [17]:
df.head(5)

,age,sex,steroid,antivirals,fatigue,malaise,anorexia,liver_big,liver_firm,spleen_palpable,spiders,ascites,varices,bilirubin,alk_phosphate,sgot,albumin,protime,histology,class
0,30,male,False,False,False,False,False,False,False,False,False,False,False,1.0,85,18,4.0,<NA>,False,live
1,50,female,False,False,True,False,False,False,False,False,False,False,False,0.9,135,42,3.5,<NA>,False,live
2,78,female,True,False,True,False,False,True,False,False,False,False,False,0.7,96,32,4.0,<NA>,False,live
3,31,female,<NA>,True,False,False,False,True,False,False,False,False,False,0.7,46,52,4.0,80,False,live
4,34,female,True,False,False,False,False,True,False,False,False,False,False,1.0,<NA>,200,4.0,<NA>,False,live


In [18]:
# I dentify how many missing values there are
df.isna().sum()

,0
age,0
sex,0
steroid,1
antivirals,0
fatigue,1
malaise,1
anorexia,1
liver_big,10
liver_firm,11
spleen_palpable,5


In [19]:
# We want to get the percentage fo Nan
df.isna().sum()/len(df) * 100

,0
age,0.000000
sex,0.000000
steroid,0.645161
antivirals,0.000000
fatigue,0.645161
malaise,0.645161
anorexia,0.645161
liver_big,6.451613
liver_firm,7.096774
spleen_palpable,3.225806


# 2. Clean the dataset
There are NaN values!

We have three options:

1. drop variables with missing values
2. drop samples with missing values
3. replace missing value with synthetic value

### case 1. Drop the veriables with missing values

In [23]:
# remove the Nan values
df.dropna(axis=0)[:5]

,age,sex,steroid,antivirals,fatigue,malaise,anorexia,liver_big,liver_firm,spleen_palpable,spiders,ascites,varices,bilirubin,alk_phosphate,sgot,albumin,protime,histology,class
5,34,female,True,False,False,False,False,True,False,False,False,False,False,0.9,95,28,4.0,75,False,live
10,39,female,False,True,False,False,False,False,True,False,False,False,False,1.3,78,30,4.4,85,False,live
11,32,female,True,True,True,False,False,True,True,False,True,False,False,1.0,59,249,3.7,54,False,live
12,41,female,True,True,True,False,False,True,True,False,False,False,False,0.9,81,60,3.9,52,False,live
13,30,female,True,False,True,False,False,True,True,False,False,False,False,2.2,57,144,4.9,78,False,live


### case 2. Drop samples with missing values


In [38]:
df.dropna(axis=1)[:5]

,age,sex,antivirals,histology,class
0,30,male,False,False,live
1,50,female,False,False,live
2,78,female,False,False,live
3,31,female,True,False,live
4,34,female,False,False,live


In [39]:
# We can also delete variables only if the amount of nan is above a threshold
df.dropna(thresh=0.8*len(df),axis=1)[:5]

,age,sex,steroid,antivirals,fatigue,malaise,anorexia,liver_big,liver_firm,spleen_palpable,spiders,ascites,varices,bilirubin,alk_phosphate,sgot,albumin,histology,class
0,30,male,False,False,False,False,False,False,False,False,False,False,False,1.0,85,18,4.0,False,live
1,50,female,False,False,True,False,False,False,False,False,False,False,False,0.9,135,42,3.5,False,live
2,78,female,True,False,True,False,False,True,False,False,False,False,False,0.7,96,32,4.0,False,live
3,31,female,<NA>,True,False,False,False,True,False,False,False,False,False,0.7,46,52,4.0,False,live
4,34,female,True,False,False,False,False,True,False,False,False,False,False,1.0,<NA>,200,4.0,False,live


## Case 3 (preferred) - we want to insert generated values

- In case of numerical values, we can replace the missing value with the average value of the column
- In case of cathegorical values we can replace the missing value with the most frequent value of the column

.fillna(value) replaces all the NaNs with values passed as argument

In [46]:
# Let's start with bollean columsn
# 1. Get columns that contain bolean value
boolean_cols = df.select_dtypes(include=bool).columns.tolist()
boolean_cols

['steroid',
 'antivirals',
 'fatigue',
 'malaise',
 'anorexia',
 'liver_big',
 'liver_firm',
 'spleen_palpable',
 'spiders',
 'ascites',
 'varices',
 'histology']

In [47]:
# 2. Get the most frequent value s
most_frequent_values = df[boolean_cols].mode().loc[0]
most_frequent_values

,0
steroid,True
antivirals,False
fatigue,True
malaise,False
anorexia,False
liver_big,True
liver_firm,False
spleen_palpable,False
spiders,False
ascites,False


In [48]:
# Replace missing content with the mode
df[boolean_cols] = df[boolean_cols].fillna(most_frequent_values)
df[:5]

,age,sex,steroid,antivirals,fatigue,malaise,anorexia,liver_big,liver_firm,spleen_palpable,spiders,ascites,varices,bilirubin,alk_phosphate,sgot,albumin,protime,histology,class
0,30,male,False,False,False,False,False,False,False,False,False,False,False,1.0,85,18,4.0,<NA>,False,live
1,50,female,False,False,True,False,False,False,False,False,False,False,False,0.9,135,42,3.5,<NA>,False,live
2,78,female,True,False,True,False,False,True,False,False,False,False,False,0.7,96,32,4.0,<NA>,False,live
3,31,female,True,True,False,False,False,True,False,False,False,False,False,0.7,46,52,4.0,80,False,live
4,34,female,True,False,False,False,False,True,False,False,False,False,False,1.0,<NA>,200,4.0,<NA>,False,live


#### Ingeger values

In [49]:
# 1. Get columns containing number
numeric = df.select_dtypes(include=int)
numeric[:5]

,age,alk_phosphate,sgot,protime
0,30,85,18,<NA>
1,50,135,42,<NA>
2,78,96,32,<NA>
3,31,46,52,80
4,34,<NA>,200,<NA>


In [50]:
# 2. integer columns
integer_columns = numeric.columns
integer_columns

Index(['age', 'alk_phosphate', 'sgot', 'protime'], dtype='object')

In [51]:
# find the median
median_of_integer_cols = df[integer_columns].median()
median_of_integer_cols

,0
age,39.0
alk_phosphate,85.0
sgot,58.0
protime,61.0


In [52]:
# replace these columns with their median
df[integer_columns] = df[integer_columns].fillna(median_of_integer_cols)
df[:5]

,age,sex,steroid,antivirals,fatigue,malaise,anorexia,liver_big,liver_firm,spleen_palpable,spiders,ascites,varices,bilirubin,alk_phosphate,sgot,albumin,protime,histology,class
0,30,male,False,False,False,False,False,False,False,False,False,False,False,1.0,85,18,4.0,61,False,live
1,50,female,False,False,True,False,False,False,False,False,False,False,False,0.9,135,42,3.5,61,False,live
2,78,female,True,False,True,False,False,True,False,False,False,False,False,0.7,96,32,4.0,61,False,live
3,31,female,True,True,False,False,False,True,False,False,False,False,False,0.7,46,52,4.0,80,False,live
4,34,female,True,False,False,False,False,True,False,False,False,False,False,1.0,85,200,4.0,61,False,live


#### Float columns

In [53]:
# lets's address the float columns
numeric = df.select_dtypes(include=float)
numeric_columns = numeric.columns
numeric_columns

Index(['bilirubin', 'albumin'], dtype='object')

In [54]:
# replace these columns with their median
# convert all floats64 to floats
df[numeric_columns] = df[numeric_columns].astype(float)

In [55]:
# interpolate
df[numeric_columns] = df[numeric_columns].interpolate(method='linear')

#### Categorical columns

In [56]:
 # get the cateforical columns
categorical_columns = df.select_dtypes(include='string').columns.tolist()
categorical_columns

['sex', 'class']

In [57]:
# get the most frequent values
most_frequent_values = df[categorical_columns].mode()
most_frequent_values

,sex,class
0,female,live


In [58]:
df[categorical_columns] = df[categorical_columns].fillna(most_frequent_values)

In [59]:
df[:4]

,age,sex,steroid,antivirals,fatigue,malaise,anorexia,liver_big,liver_firm,spleen_palpable,spiders,ascites,varices,bilirubin,alk_phosphate,sgot,albumin,protime,histology,class
0,30,male,False,False,False,False,False,False,False,False,False,False,False,1.0,85,18,4.0,61,False,live
1,50,female,False,False,True,False,False,False,False,False,False,False,False,0.9,135,42,3.5,61,False,live
2,78,female,True,False,True,False,False,True,False,False,False,False,False,0.7,96,32,4.0,61,False,live
3,31,female,True,True,False,False,False,True,False,False,False,False,False,0.7,46,52,4.0,80,False,live


In [60]:
# Final check
df.isnull().values.any() # this should be False

np.False_

# 2. Encode the features
We need to encode the target variable through labeling

In [61]:
# 1. initialize the label encoder
le = sklearn.preprocessing.LabelEncoder()

In [62]:
# 2. Encode the target class
# Fit convert string to number & transfor
df['class'] = le.fit_transform(df['class'])

 We need to encode cathegorical features through one-hot encoding

In [63]:
# get columns containing cathegorical features
categorical_features = df.select_dtypes(include='string').columns.tolist()
categorical_features

['sex']

In [64]:
# one-hot encode the categorical features
df = pd.get_dummies(df, prefix=categorical_features)
df[:5]

,age,steroid,antivirals,fatigue,malaise,anorexia,liver_big,liver_firm,spleen_palpable,spiders,...,varices,bilirubin,alk_phosphate,sgot,albumin,protime,histology,class,sex_female,sex_male
0,30,False,False,False,False,False,False,False,False,False,...,False,1.0,85,18,4.0,61,False,1,False,True
1,50,False,False,True,False,False,False,False,False,False,...,False,0.9,135,42,3.5,61,False,1,True,False
2,78,True,False,True,False,False,True,False,False,False,...,False,0.7,96,32,4.0,61,False,1,True,False
3,31,True,True,False,False,False,True,False,False,False,...,False,0.7,46,52,4.0,80,False,1,True,False
4,34,True,False,False,False,False,True,False,False,False,...,False,1.0,85,200,4.0,61,False,1,True,False


In [65]:
# 3. Let's find the ooutliers
# 3.1 isolation forests
# Initialized the isolation forest

isoforest = sklearn.ensemble.IsolationForest(n_estimators=1000, contamination=0.01, random_state=0)
# random_state=to stop randomness


In [66]:
# for each sample get an anomaly score
res = isoforest.fit_predict(df.to_numpy())
res[res==-1]

array([-1, -1])

In [67]:
# Find outliers with PCA
pca = sklearn.decomposition.PCA(n_components=0.9999)

In [68]:
# apply pca
X_pca = pca.fit_transform(df)

In [69]:
# invert pca
X_ori = pca.inverse_transform(X_pca)

In [72]:
#  define anomaly score as the sum of the absolute distances
anomaly_score = np.abs(df.to_numpy()-X_ori).sum(1)

In [73]:
anomaly_score

array([4.257120094857969, 3.483297673117139, 1.753849211656837,
       1.9933958330522419, 1.254265844106791, 1.1694381613686615,
       5.555806022682493, 1.0324252117221375, 2.9921763854531163,
       1.2993078266405715, 3.416006343768003, 3.596288689332473,
       3.3086025091232503, 3.3956802460224433, 2.5751272911672265,
       3.200063554233521, 1.549763308884244, 3.22016012400328,
       1.8985973388560002, 3.609386733941557, 3.7808480333459578,
       4.2097689986864335, 0.9764544264680654, 1.1852112669328523,
       4.277626832026586, 1.879344612588713, 4.15769005965371,
       3.3217971389957683, 3.0384168362321864, 2.388175158723415,
       5.004256515574848, 2.5814765040871905, 4.188555473411109,
       3.613651285169248, 1.763836189722548, 3.8481916267463654,
       2.550507982092612, 3.46631961507377, 1.5286656216488328,
       3.263159731775886, 2.5565538904639373, 1.4896389919912882,
       1.0604296995731897, 2.3648529264168165, 1.0180075434835052,
       2.21147665531

In [75]:
threshold = np.quantile(anomaly_score, 0.99)

# get the ids of the anomalous values
anomalous_ids = np.argwhere(anomaly_score > threshold).squeeze()


In [76]:
df.iloc[anomalous_ids]

,age,steroid,antivirals,fatigue,malaise,anorexia,liver_big,liver_firm,spleen_palpable,spiders,...,varices,bilirubin,alk_phosphate,sgot,albumin,protime,histology,class,sex_female,sex_male
6,51,False,False,True,False,True,True,False,True,True,...,False,0.95,85,58,4.133333,61,False,0,True,False
153,53,False,False,True,False,False,True,False,True,True,...,True,1.50,81,19,4.100000,48,True,1,False,True


In [77]:
# 4. Normalize the features
# split input variable from output variables
x = df[list(set(df.columns)-set(['class']))]
y = df['class']

In [79]:
# define standard scaler
scaler = sklearn.preprocessing.StandardScaler()
# normalize features
x = scaler.fit_transform(x)

In [ ]:
# split train/ test

In [80]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state=0)


In [81]:
x_train.shape, x_test.shape

((124, 20), (31, 20))

### Train random forest

In [83]:
rf = sklearn.ensemble.RandomForestClassifier(n_estimators=100)

In [84]:
rf.fit(x_train, y_train)


RandomForestClassifier()

In [85]:
# predict on test set
y_estim = rf.predict(x_test)


In [86]:
conf_mat = sklearn.metrics.confusion_matrix(y_test, y_estim)
conf_mat

array([[ 4,  5],
       [ 0, 22]])

In [87]:
# Comput the accuracy
acc = sklearn.metrics.accuracy_score(y_test, y_estim)
acc

0.8387096774193549