<a href="https://colab.research.google.com/github/nawroz-m/ML_learning/blob/main/medical_cost_personal_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Predict the cost of insurance based on the dataset availabe
1. Praper the datase
2. Praper the training and testing dataset
3. Create the model
4. Evaluate the model

In [1]:
import pandas as pd

In [3]:
# 1. Praper the dataset
insurance = pd.read_csv("https://raw.githubusercontent.com/stedy/Machine-Learning-with-R-datasets/refs/heads/master/insurance.csv")
insurance.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [6]:
# Encode non numerical columns using pandas dummy function
insurance_one_hot = pd.get_dummies(insurance, dtype=int)
insurance_one_hot.head()

age     bmi  children      charges  sex_female  sex_male  smoker_no  \
0   19  27.900         0  16884.92400           1         0          0   
1   18  33.770         1   1725.55230           0         1          1   
2   28  33.000         3   4449.46200           0         1          1   
3   33  22.705         0  21984.47061           0         1          1   
4   32  28.880         0   3866.85520           0         1          1   

   smoker_yes  region_northeast  region_northwest  region_southeast  \
0           1                 0                 0                 0   
1           0                 0                 0                 1   
2           0                 0                 0                 1   
3           0                 0                 1                 0   
4           0                 0                 1                 0   

   region_southwest  
0                 1  
1                 0  
2                 0  
3                 0  
4                 0

In [12]:
# Prepare the Independent Variable(Feature) and Dependent Variable(Label)
X = insurance_one_hot.drop(columns="charges") # Feature
y = insurance_one_hot["charges"] # Label

In [21]:
len(X), len(y)

(1338, 1338)

In [22]:
# 2. Prepare the training and tesing dataset
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42) #42 to have a constant shuffle


In [24]:
len(X_train), len(y_train), len(X_test), len(y_test)

(1070, 1070, 268, 268)

## 3. Create a model

In [25]:
import tensorflow as tf

In [28]:
tf.random.set_seed(42)
# 1. Create a model using Sequential API
model = tf.keras.Sequential([
    tf.keras.layers.Dense(100, name="Input_layer_1"),
    tf.keras.layers.Dense(1, name="Output_layer"),
], name="Insurance_cost_pred")

# 2. Compile the model
model.compile(optimizer=tf.keras.optimizers.SGD(),
              loss=tf.keras.losses.mae,
              metrics=["mae"])

# 3. Fit the model
model.fit(X_train, y_train, epochs=100)


Epoch 1/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 10016.9863 - mae: 10016.9863   
Epoch 2/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7571.1182 - mae: 7571.1182 
Epoch 3/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7883.4253 - mae: 7883.4253 
Epoch 4/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7370.7720 - mae: 7370.7720 
Epoch 5/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7559.4126 - mae: 7559.4126 
Epoch 6/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7306.8711 - mae: 7306.8711 
Epoch 7/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7661.5630 - mae: 7661.5630 
Epoch 8/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7713.4199 - mae: 7713.4199 
Epoch 9/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7637.7959 - mae: 7637.7959 
Epoch 10/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7399.7573 - mae: 7399.7573 
Epoch 11/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7888.1924 - mae: 7888.1924 
Epoch 12/100
34/34 ━━━━━━━━━━━━━━━━━━

In [29]:
y_median = tf.keras.ops.median(y_train)
y_mean = tf.keras.ops.mean(y_train)
y_mean, y_median

(<tf.Tensor: shape=(), dtype=float64, numpy=13346.089736364485>,
 <tf.Tensor: shape=(), dtype=float64, numpy=9575.4421>)

In [30]:
# Evaluate the model
model.evaluate(X_train, y_train)

34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 8342.4746 - mae: 8342.4746 


[8159.6318359375, 8159.6318359375]

In [32]:
# Make some prediction
y_pred = model.predict(X_test)
y_pred

9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step 


array([[15498.739 ],
       [11302.192 ],
       [24673.469 ],
       [16077.461 ],
       [ 8968.777 ],
       [11096.062 ],
       [ 5166.1865],
       [21021.291 ],
       [ 8226.911 ],
       [17211.312 ],
       [14002.086 ],
       [13932.869 ],
       [ 9537.129 ],
       [20468.92  ],
       [23596.7   ],
       [20146.67  ],
       [17452.037 ],
       [19758.348 ],
       [15388.354 ],
       [17385.59  ],
       [ 9622.18  ],
       [14457.07  ],
       [ 4934.941 ],
       [ 6853.547 ],
       [17786.742 ],
       [17734.557 ],
       [19557.973 ],
       [ 9876.565 ],
       [16237.689 ],
       [ 4928.7207],
       [14682.234 ],
       [18646.902 ],
       [ 6365.107 ],
       [10588.671 ],
       [ 7913.5684],
       [14589.174 ],
       [ 6311.348 ],
       [14056.468 ],
       [20984.154 ],
       [15649.525 ],
       [ 7934.244 ],
       [ 6801.0747],
       [18753.775 ],
       [18894.248 ],
       [11434.837 ],
       [19287.24  ],
       [ 7334.083 ],
       [ 8757

In [35]:
# Evaluate the MAE and MSE
mae = tf.keras.metrics.mae(y_true=y_test, y_pred=tf.squeeze(y_pred))
mse = tf.keras.metrics.mse(y_true=y_test, y_pred=tf.squeeze(y_pred))
mae, mse

(<tf.Tensor: shape=(), dtype=float32, numpy=8068.16162109375>,
 <tf.Tensor: shape=(), dtype=float32, numpy=106252592.0>)